package hu.lakospeter.macremotecontrol;


public enum RemoteControlAction {
    VOLUME_UP_PRESSED,
    VOLUME_UP_HOLD_STARTED,
    VOLUME_UP_HOLD_STOPPED,
    VOLUME_DOWN_PRESSED,
    VOLUME_DOWN_HOLD_STARTED,
    VOLUME_DOWN_HOLD_STOPPED,
    PREVIOUS_PRESSED,
    PREVIOUS_HOLD_STARTED,
    PREVIOUS_HOLD_STOPPED,
    NEXT_PRESSED,
    NEXT_HOLD_STARTED,
    NEXT_HOLD_STOPPED,
    PLAY_PAUSE_PRESSED,
    PLAY_PAUSE_HELD,
    MENU_PRESSED,
    MENU_HELD,
    SELECT_PRESSED
}
